// Generated by scripts/build/gen-lua-builtin.py — DO NOT EDIT.
// Source: deploy/apps/ (the same .lua the Lua Store serves).
// Seeded built-ins: a downloaded <data>/apps/<id>.lua always wins.
#pragma once

struct LuaBuiltinApp { const char* id; const char* name; const char* ver; const char* src; };

static const char kLuaSrc_monitor[] = R"WADALUA(-- RF Monitor (Lua) — live RSSI/noise chart with a dBm axis, link-margin grade,
-- RX rate, radio parameters and the recently-heard feed. The page scrolls, so
-- the whole feed is reachable on short screens.
local ui, sys, mesh, timer = wada.ui, wada.sys, wada.mesh, wada.timer
local C = ui.colors
local app = {}

local RSSI_MIN, RSSI_MAX = -130, -20
local TYPE = { [1]="ADV", [2]="TXT", [3]="ACK", [4]="GRP", [5]="REQ", [6]="RSP", [7]="PTH", [8]="TRC" }
local TCOL = { [1]=0xA784E0, [2]=0x4F9DF7, [3]=0x53C06B, [4]=0x35C9C9, [5]=0xE8A33D, [6]=0xF2793C }

local W, narrow
local legend, chart, metrics, radio_lbl, feed_hdr, feed_rows = nil, nil, nil, nil, nil, {}
local peak, rx0, t0

local function fmt_ago(ms)
  local s = ms // 1000
  if s < 60 then return s .. "s" end
  if s < 3600 then return (s // 60) .. "m" end
  return (s // 3600) .. "h"
end

local function grade(m)
  if m >= 20 then return "excellent", C.good end
  if m >= 10 then return "good",      C.good end
  if m >= 5  then return "fair",      0xE8A33D end
  if m > 0   then return "weak",      C.bad end
  return "no margin", C.bad
end

local function refresh()
  local st = mesh.stats()
  if st.rssi > peak then peak = st.rssi end
  chart:push(1, math.floor(st.rssi))
  chart:push(2, math.floor(st.noise))

  local mg = st.rssi - st.noise
  local gtxt, gcol = grade(mg)
  local mins = math.max((sys.millis() - t0) / 60000, 1 / 60)

  legend:set(string.format("RSSI %.0f   noise %.0f   peak %.0f dBm", st.rssi, st.noise, peak))
  metrics:set(string.format("margin %.0f dB (%s)   RX ~%.0f/min", mg, gtxt, (st.rx_pkts - rx0) / mins))
  metrics:color(gcol)
  radio_lbl:set(string.format("%.3f MHz  SF%d  BW %.0f   %d rx / %d err / %d drop   duty %d%%",
                              st.freq, st.sf, st.bw, st.rx_pkts, st.rx_err, st.rx_dropped, st.duty_pct))

  local log = mesh.rx_log()
  for i = 1, #feed_rows do
    local r = log[i]
    if r then
      local nm = TYPE[r.type] or ("t" .. r.type)
      if narrow then
        feed_rows[i]:set(string.format("%-4s %-3s %4d %5.1f %s", fmt_ago(r.ago_ms), nm, r.rssi, r.snr,
                                       r.hops == 0 and "dir" or (r.hops .. "h")))
      else
        feed_rows[i]:set(string.format("%-5s %-3s  %4d dBm  %5.1f dB  %s", fmt_ago(r.ago_ms), nm, r.rssi, r.snr,
                                       r.hops == 0 and "direct" or (r.hops .. (r.hops == 1 and " hop" or " hops"))))
      end
      feed_rows[i]:color(TCOL[r.type] or C.text)
    else
      feed_rows[i]:set(i == 1 and #log == 0 and "listening - nothing heard yet" or "")
      feed_rows[i]:color(C.sub)
    end
  end
end

function app.on_open(w, h)
  W, narrow = w, w < 280
  ui.scroll(true)                      -- the feed runs past the screen; let it scroll
  local LH12 = ui.text_h(12)           -- real line heights, no guessing
  local st = mesh.stats()
  rx0, t0, peak = st.rx_pkts, sys.millis(), st.rssi

  local y = 4
  legend = ui.label("", 4, y, 12, C.accent); legend:width(w - 10); y = y + LH12 + 4

  local AX, ch_h = 38, narrow and 62 or 76
  chart = ui.chart(w - AX - 8, ch_h, 72, C.accent, C.sub)
  chart:pos(AX, y)
  chart:range(RSSI_MIN, RSSI_MAX)
  chart:axis(3, AX)
  y = y + ch_h + 6

  metrics = ui.label("", 4, y, 12, C.text); metrics:width(w - 10)
  y = y + LH12 * (narrow and 2 or 1) + 3
  radio_lbl = ui.label("", 4, y, 12, C.sub); radio_lbl:width(w - 10)
  y = y + LH12 * (narrow and 3 or 2) + 5

  feed_hdr = ui.label(narrow and "recently heard" or "recently heard (newest first)", 4, y, 12, C.sub)
  feed_hdr:width(w - 10)
  y = y + LH12 + 3
  for i = 1, 16 do                     -- scrolling means we can show the whole ring
    feed_rows[i] = ui.label("", 4, y, 12, C.text)
    feed_rows[i]:width(w - 10)
    y = y + LH12 + 2
  end

  refresh()
  timer.every(1000)
end

function app.on_tick(dt) refresh() end

return app
)WADALUA";
static const char kLuaSrc_airtime[] = R"WADALUA(-- Airtime (Lua) — channel utilization over time: live + average bars with a %
-- axis, rx/tx air split, duty ceiling, tx budget and packet counters.
local ui, sys, mesh, timer = wada.ui, wada.sys, wada.mesh, wada.timer
-- Translate through the device's language table (wada.sys.tr, added for #257).
-- Older firmware has no sys.tr, so fall back to the English string rather than error.
local tr = sys.tr or function(x) return x end
local C = ui.colors
local app = {}

local W, narrow
local head, sub, legend, detail, chart
local base, t0, last
local peak_pct = 0

local function restart_window()
  local st = mesh.stats()
  base = { rx = st.rx_air_s, tx = st.tx_air_s }
  t0 = sys.millis()
  last = { ms = t0, rx = st.rx_air_s, tx = st.tx_air_s }
  peak_pct = 0
  chart:fill(1, 0)
  chart:fill(2, 0)
  head:set(tr("sampling..."))
  head:color(C.accent)
  sys.toast(tr("window restarted"), 900)
end

local function refresh()
  local st = mesh.stats()
  local now = sys.millis()
  local wall = (now - t0) / 1000
  if wall < 0.5 then return end

  local rx_air, tx_air = st.rx_air_s - base.rx, st.tx_air_s - base.tx
  local avg = math.min(100, (rx_air + tx_air) * 100 / wall)

  local dw = (now - last.ms) / 1000
  local live = 0
  if dw > 0 then
    live = math.min(100, ((st.rx_air_s - last.rx) + (st.tx_air_s - last.tx)) * 100 / dw)
  end
  last = { ms = now, rx = st.rx_air_s, tx = st.tx_air_s }
  if live > peak_pct then peak_pct = live end

  chart:push(1, math.floor(live))
  chart:push(2, math.floor(avg))

  head:set(string.format(tr("channel busy %.1f%%"), live))
  head:color(live > 50 and C.bad or live > 20 and 0xE8A33D or C.good)
  sub:set(string.format(tr("avg %.1f%%   peak %.1f%%   over %ds"), avg, peak_pct, math.floor(wall)))
  if narrow then
    detail:set(string.format("air rx %ds / tx %ds\nduty %d%%   budget %dms\ntx %d  rx %d  err %d",
      rx_air, tx_air, st.duty_pct, st.tx_budget_ms, st.tx_pkts, st.rx_pkts, st.rx_err))
  else
    detail:set(string.format("air rx %ds / tx %ds   duty %d%%   budget %dms\ntx %d   rx %d   err %d   drop %d   SF%d",
      rx_air, tx_air, st.duty_pct, st.tx_budget_ms, st.tx_pkts, st.rx_pkts, st.rx_err, st.rx_dropped, st.sf))
  end
end

function app.on_open(w, h)
  W, narrow = w, w < 280
  local LH12, LH16 = ui.text_h(12), ui.text_h(16)

  local y = 2
  head = ui.label(tr("sampling..."), 4, y, 16, C.accent); head:width(w - 86)
  ui.button(tr("Reset"), w - 76, y, 70, 30, function() restart_window() end)   -- top-right
  y = y + LH16 + 4
  sub = ui.label("", 4, y, 12, C.sub); sub:width(w - 10)
  y = y + LH12 + 5

  local AX = 34
  local det_lines = narrow and 3 or 2
  local ch_h = h - y - (det_lines * LH12) - LH12 - 14
  if ch_h < 48 then ch_h = 48 end
  if ch_h > 110 then ch_h = 110 end
  chart = ui.chart(w - AX - 8, ch_h, 60, C.accent, 0x4F9DF7, true)
  chart:pos(AX, y)
  chart:range(0, 100)
  chart:axis(3, AX)
  y = y + ch_h + 4

  legend = ui.label(tr("teal = now   blue = average"), 4, y, 12, C.sub); legend:width(w - 10)
  y = y + LH12 + 2
  detail = ui.label("", 4, y, 12, C.text); detail:width(w - 10)

  local st = mesh.stats()
  base = { rx = st.rx_air_s, tx = st.tx_air_s }
  t0 = sys.millis()
  last = { ms = t0, rx = st.rx_air_s, tx = st.tx_air_s }
  timer.every(1000)
end

function app.on_tick(dt) refresh() end

return app
)WADALUA";
static const char kLuaSrc_snake[] = R"WADALUA(-- Snake — wada.* reference app. Swipe (or trackball) to steer; eat the red
-- food, don't bite yourself. Tap after a game over to play again.
local ui, sys, store, timer = wada.ui, wada.sys, wada.store, wada.timer
local C = ui.colors

local CELL = 14
local app = {}
local cv, score_lbl
local cols, rows, px_w, px_h
local body, len, dx, dy, ndx, ndy, fx, fy
local score, hiscore, running, over

local function place_food()
  repeat
    fx, fy = sys.random(0, cols - 1), sys.random(0, rows - 1)
    local clash = false
    for i = 1, len do
      if body[i].x == fx and body[i].y == fy then clash = true break end
    end
  until not clash
end

local function reset()
  len, score, over, running = 3, 0, false, false
  dx, dy, ndx, ndy = 1, 0, 1, 0
  body = {}
  local cx, cy = math.floor(cols / 2), math.floor(rows / 2)
  for i = 1, len do body[i] = { x = cx - i + 1, y = cy } end
  place_food()
end

local function scoreline()
  score_lbl:set(string.format("Score %d   Best %d%s", score, hiscore,
                              running and "" or (over and "   -  tap to retry" or "   -  swipe to start")))
end

local function draw()
  cv:fill(0x101418)
  cv:rect(fx * CELL + 2, fy * CELL + 2, CELL - 4, CELL - 4, C.bad, true, 4)
  for i = len, 1, -1 do
    cv:rect(body[i].x * CELL + 1, body[i].y * CELL + 1, CELL - 2, CELL - 2,
            i == 1 and C.accent or C.good, true, 3)
  end
  if over then
    cv:text(math.floor(px_w / 2) - 40, math.floor(px_h / 2) - 10, "GAME OVER", C.text, 16)
  end
end

local function step()
  dx, dy = ndx, ndy
  local head = body[1]
  local nx, ny = head.x + dx, head.y + dy
  if nx < 0 or ny < 0 or nx >= cols or ny >= rows then over = true end
  if not over then
    for i = 1, len - 1 do
      if body[i].x == nx and body[i].y == ny then over = true break end
    end
  end
  if over then
    running = false
    if score > hiscore then
      hiscore = score
      store.set("hiscore", hiscore)
      sys.toast("New high score: " .. hiscore, 1600)
    end
    scoreline()
    draw()
    return
  end
  table.insert(body, 1, { x = nx, y = ny })
  if nx == fx and ny == fy then
    len = len + 1
    score = score + 10
    place_food()
    scoreline()
  else
    body[#body] = nil
  end
  draw()
end

function app.on_open(w, h)
  hiscore = store.get("hiscore", 0)
  cols = math.floor(w / CELL)
  rows = math.floor((h - 26) / CELL)
  px_w, px_h = cols * CELL, rows * CELL
  score_lbl = ui.label("", 4, 4, 14, C.text)
  cv = ui.canvas(px_w, px_h)
  cv:pos(math.floor((w - px_w) / 2), 26)
  reset()
  scoreline()
  draw()
  timer.every(120)
end

function app.on_input(ev)
  if ev.type == "swipe" then
    local d = ev.dir
    if     d == "up"    and dy ~= 1  then ndx, ndy = 0, -1
    elseif d == "down"  and dy ~= -1 then ndx, ndy = 0, 1
    elseif d == "left"  and dx ~= 1  then ndx, ndy = -1, 0
    elseif d == "right" and dx ~= -1 then ndx, ndy = 1, 0
    end
    if not running and not over then running = true; scoreline() end
  elseif ev.type == "down" and over then
    reset()
    scoreline()
    draw()
  end
end

function app.on_tick(dt)
  if running and not over then step() end
end

function app.on_close()
  -- high score is already persisted on set; nothing to tear down (the host
  -- frees every widget and the canvas with the app)
end

return app
)WADALUA";
static const char kLuaSrc_sdktest[] = R"WADALUA(-- SDK self-test. Exercises the extended SDK so the results can be read off the
-- screen instead of inferred from a build log. Published to the store as a
-- developer/bench tool.
--
-- 1.2 adds wada.crypto (checked against published RFC vectors, so a PASS here is
-- real evidence and not just "it returned something"), wada.mesh.channels, and
-- wada.mesh.send_dm.
-- 1.3 adds the discovery surface (wada.mesh.discover / discovered), packet
-- identity in rx_log, exact micro-degree coordinates, wada.ui.input and the
-- windowed wada.fs.read.
-- 1.6 adds wada.sd.list: capability reporting, traversal rejection, root
-- metadata, and a nested directory listing when the card contains one.
-- 1.7 adds storage-neutral wada.audio capability and API-shape checks. Playback
-- stays manual so opening the bench test never emits sound unexpectedly.
-- 1.5 uses wada.ui.text_lines() to measure instead of estimating, where the
-- firmware has it. That call was added because of the 1.3 bug below: an app
-- could ask how tall a line is but not how wide, so laying out rows meant
-- guessing whether text would wrap. Falls back to the 1.4 estimate on older
-- firmware, so it still lays out correctly there.
-- 1.4 fixes rows drawing on top of one another. label:width() turns wrapping
-- on, so any line wider than the screen became two lines while the caller still
-- advanced by one, and the next row landed on top. Reported with a photo of the
-- channels line sitting across the contacts line. row() now owns the cursor and
-- advances by the height the text actually needs.
local ui, sys, store, timer = wada.ui, wada.sys, wada.store, wada.timer
local C = ui.colors

local app = {}
local rows, keyline, sendline, dmline, msgline = {}, nil, nil, nil, nil
local discline, inputline = nil, nil
local W = 300

-- row() owns the vertical cursor. Every caller used to pass a y and then add a
-- hand-picked constant, which is only correct while the text fits on one line.
-- An app cannot measure rendered text, so the wrapped line count is estimated
-- from a deliberately pessimistic character width: over-estimating costs a
-- little whitespace, under-estimating overlaps the next row.
local LH, GAP = 14, 3
local cy = 4
local function row(text, color, extra_gap)
  local l = ui.label(text, 6, cy, 12, color or C.text)
  l:width(W - 12)
  rows[#rows + 1] = l
  local n
  if ui.text_lines then
    n = ui.text_lines(tostring(text), W - 12, 12)     -- measured: exact
  else
    local cpl = math.max(16, (W - 12) // 7)           -- older firmware: estimate
    n = 0
    for seg in (tostring(text) .. "\n"):gmatch("(.-)\n") do
      n = n + math.max(1, math.ceil(#seg / cpl))
    end
  end
  cy = cy + math.max(1, n or 1) * LH + GAP + (extra_gap or 0)
  return l
end
local function yn(v) return v and "yes" or "NO" end

function app.on_open(w, h)
  W = w or 300
  ui.scroll(true)
  cy = 4
  local y

  local c = sys.caps()
  row("caps: sdk_ext=" .. yn(c.sdk_ext) .. "  kbd=" .. yn(c.keyboard) ..
         "  touch=" .. yn(c.touch) .. "  sd=" .. yn(c.sd), C.accent)
    row("caps: sd_list=" .. yn(c.sd_list) .. "  discover=" .. yn(c.discover) ..
      "  input=" .. yn(c.input) ..
         "  rx_identity=" .. yn(c.rx_identity), C.accent)
    row("caps: audio=" .. yn(c.audio) .. "  wav=" .. yn(c.audio_wav) ..
           "  mp3=" .. yn(c.audio_mp3) .. "  audio_sd=" .. yn(c.audio_sd), C.accent)
    if c.audio then
      local api_ok = wada.audio and type(wada.audio.play) == "function" and
                     type(wada.audio.pause) == "function" and
                     type(wada.audio.resume) == "function" and
                     type(wada.audio.stop) == "function" and
                     type(wada.audio.status) == "function"
      local status = api_ok and wada.audio.status() or nil
      api_ok = api_ok and type(status) == "table" and type(status.state) == "string"
      row("wada.audio API: " .. (api_ok and ("PASS (" .. status.state .. ")") or "FAIL"),
          api_ok and C.good or C.bad)
    else
      row("wada.audio: unavailable on this board", C.sub)
    end
  row("layout: " .. (ui.text_lines and "measured (ui.text_lines)" or "estimated (older firmware)"),
      ui.text_lines and C.good or C.sub)
  -- crypto: published test vectors, so this is checkable rather than merely alive
  if wada.crypto then
    local hex = wada.crypto.hex
    local k20 = string.rep(string.char(0x0b), 20)
    local checks = {
      { "sha256('abc')", hex(wada.crypto.sha256("abc")),
        "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad" },
      { "sha1('abc')", hex(wada.crypto.sha1("abc")),
        "a9993e364706816aba3e25717850c26c9cd0d89d" },
      { "hmac_sha1 RFC2202#1", hex(wada.crypto.hmac_sha1(k20, "Hi There")),
        "b617318655057264e28bc0b6fb378c8ef146be00" },
      { "hmac_sha256 RFC4231#1", hex(wada.crypto.hmac_sha256(k20, "Hi There")),
        "b0344c61d8db38535ca8afceaf0bf12b881dc200c9833da726e9376c2e32cff7" },
    }
    local allok = true
    for _, t in ipairs(checks) do
      local ok = (t[2] == t[3])
      if not ok then allok = false end
      row("crypto " .. t[1] .. ": " .. (ok and "PASS" or ("FAIL got " .. tostring(t[2]):sub(1, 16))),
          ok and C.good or C.bad)
    end
    -- The point of having it in C: this loop would blow the instruction budget in Lua.
    local t0 = sys.millis()
    for _ = 1, 200 do wada.crypto.hmac_sha1(k20, "Hi There") end
    row(string.format("crypto: 200 x hmac_sha1 in %d ms%s", sys.millis() - t0,
        allok and "" or "  (VECTORS FAILED)"), allok and C.good or C.bad)
  else
    row("wada.crypto: MISSING", C.bad)
  end

  -- channel discovery
  local chans = wada.mesh.channels and wada.mesh.channels() or nil
  if chans then
    local names = table.concat(chans, ", ")
    row("channels(): " .. #chans .. "  " .. names:sub(1, 60), C.text)
  else
    row("wada.mesh.channels: MISSING", C.bad)
  end

  if not c.sdk_ext then
    row("extended SDK is OFF on this board - stopping here.", C.sub)
    return
  end

  -- contacts, so send_dm has a target to name. 1.3 also checks the pubkey field.
  local cts = wada.mesh.contacts()
  local first = cts[1] and cts[1].name or nil
  row("contacts: " .. #cts .. (first and ("  first=" .. first) or ""), C.text)
  if cts[1] then
    local pk = cts[1].pubkey
    row("contacts[1].pubkey: " .. tostring(pk) ..
           (type(pk) == "string" and #pk == 8 and "  PASS" or "  FAIL"),
        (type(pk) == "string" and #pk == 8) and C.good or C.bad)
  end

  local me = wada.mesh.self()
  row("self: " .. tostring(me.name) .. "  pubkey=" .. tostring(me.pubkey), C.text)
  -- Exact coordinates. Lua's floats here are 32-bit, so an app that logs a track
  -- must use the _e6 integers; this proves they are present and consistent.
  local fix = sys.gps()
  if fix then
    local drift = math.abs(fix.lat_e6 / 1e6 - fix.lat)
    row(string.format("gps: %d,%d e6  alt %dm  %d sats  drift %.6f  %s",
        fix.lat_e6, fix.lon_e6, fix.alt_m or 0, fix.sats, drift,
        drift < 0.001 and "PASS" or "FAIL"), drift < 0.001 and C.good or C.bad)
  else
    row("gps: no fix (normal indoors)", C.sub)
  end

  -- rx_log identity: adverts carry a real public key, addressed frames carry
  -- one-byte hashes, everything else carries nothing. All three are correct.
  local log = wada.mesh.rx_log()
  local withpk, withsrc = 0, 0
  for _, r in ipairs(log) do
    if r.pubkey then withpk = withpk + 1 end
    if r.src then withsrc = withsrc + 1 end
  end
  row(string.format("rx_log: %d frames, %d with a pubkey (adverts), %d with src/dst",
      #log, withpk, withsrc), #log > 0 and C.text or C.sub)
  -- fs: windowed read. Writes once (the 1/sec limit means one write per open).
  if wada.fs then
    local probe = "0123456789abcdef"
    wada.fs.write("sdktest.bin", probe)
    local part, total = wada.fs.read("sdktest.bin", 4, 4)
    local ok = (part == "4567" and total == #probe)
    row("fs.read(name,4,4): " .. tostring(part) .. " total=" .. tostring(total) ..
           (ok and "  PASS" or "  FAIL"), ok and C.good or C.bad)
  end

  -- Physical SD listing is read-only and independently feature-detected. A
  -- supported board with no inserted card is a normal bench state, not a test
  -- failure; API shape and path rejection can still be checked separately.
  if c.sd_list then
    if not wada.sd or not wada.sd.list then
      row("wada.sd.list: MISSING despite caps", C.bad)
    else
      local guard_ok, guard_failure = true, nil
      local bad_paths = { "/..", "/.", "/a/../b", "/a//b", "/a/", "relative", "/a\\b" }
      for _, path in ipairs(bad_paths) do
        local rejected, baderr = wada.sd.list(path)
        if rejected ~= nil or baderr ~= "bad path" then
          guard_ok = false
          guard_failure = path .. " -> " .. tostring(baderr)
          break
        end
      end
      row("sd traversal guard: " .. (guard_ok and "PASS" or ("FAIL " .. guard_failure)),
          guard_ok and C.good or C.bad)

      local entries, err = wada.sd.list("/")
      if not entries then
        local note = err == "busy" and " (retry later)" or " (no readable card)"
        row("sd.list('/'): " .. tostring(err) .. note, C.sub)
      else
        local metadata_ok, first_dir = true, nil
        for _, entry in ipairs(entries) do
          if type(entry.name) ~= "string" or
             (entry.type ~= "file" and entry.type ~= "dir") or
             type(entry.size) ~= "number" or type(entry.mtime) ~= "number" then
            metadata_ok = false
          end
          if not first_dir and entry.type == "dir" then first_dir = entry.name end
        end
        row("sd.list('/'): " .. #entries .. " entries, metadata " ..
               (metadata_ok and "PASS" or "FAIL") ..
               (entries.truncated and " (truncated)" or ""),
            metadata_ok and C.good or C.bad)
        if first_dir then
          local nested, nested_err = wada.sd.list("/" .. first_dir)
          row("sd.list('/" .. first_dir .. "'): " ..
                 (nested and (#nested .. " entries PASS") or ("FAIL " .. tostring(nested_err))),
              nested and C.good or C.bad)
        else
          row("sd nested listing: no directory on card to test", C.sub)
        end
      end
    end
  else
    row("wada.sd.list: unavailable on this board", C.sub)
  end

  sendline = row("mesh.send: not tried yet", C.sub)
  dmline   = row("mesh.send_dm: not tried yet", C.sub)
  msgline  = row("on_message: waiting (needs the read permissions)", C.sub)
  y = cy + 4
  ui.button("Send to Public", 6, y, 120, 30, function()
    local ok, err = wada.mesh.send("Public", "wadamesh SDK self-test")
    sendline:set("mesh.send: " .. tostring(ok) .. "  " .. tostring(err))
    sendline:color(ok and C.good or C.bad)
  end)
  ui.button("DM first contact", 132, y, 130, 30, function()
    if not first then dmline:set("mesh.send_dm: no contacts to target"); dmline:color(C.bad); return end
    local ok, err = wada.mesh.send_dm(first, "wadamesh SDK self-test (DM)")
    dmline:set("mesh.send_dm -> " .. first .. ": " .. tostring(ok) .. "  " .. tostring(err))
    dmline:color(ok and C.good or C.bad)
  end)
  cy = y + 38
  discline  = row("mesh.discover: not tried yet", C.sub)
  inputline = row("ui.input: not tried yet", C.sub)
  -- Probing TRANSMITS and makes every neighbour reply, so it is a button, not
  -- something this app does on open.
  y = cy + 4
  ui.button("Probe", 6, y, 90, 30, function()
    local tag, err = wada.mesh.discover()
    if not tag then
      discline:set("mesh.discover: " .. tostring(err)); discline:color(C.bad); return
    end
    discline:set("mesh.discover: sent, waiting for replies..."); discline:color(C.text)
  end)
  ui.button("Results", 102, y, 90, 30, function()
    local hits = wada.mesh.discovered()
    if #hits == 0 then
      discline:set("discovered(): nothing yet - probe, then wait a few seconds")
      discline:color(C.sub); return
    end
    local h = hits[1]
    discline:set(string.format("discovered(): %d  first %s snr %.1f/%.1f %s",
      #hits, h.name or h.pubkey, h.snr, h.their_snr, h.direct and "direct" or (h.hops .. "h")))
    discline:color(C.good)
  end)
  y = y + 34
  ui.button("Beep", 6, y, 70, 30, function() sys.beep() end)
  ui.button("Input", 82, y, 90, 30, function()
    ui.input("Type anything", "hello", function(text)
      inputline:set("ui.input -> " .. (text and ("'" .. text .. "'") or "cancelled"))
      inputline:color(text and C.good or C.sub)
    end)
  end)
end

function app.on_input(ev)
  if ev.type == "key" and keyline then
    keyline:set("keys: got '" .. tostring(ev.key) .. "'")
    keyline:color(C.good)
  end
end

-- Proves the kind field and that DMs/rooms reach an app at all, not just channels.
function app.on_message(m)
  if not msgline then return end
  msgline:set("on_message: kind=" .. tostring(m.kind) .. " from=" .. tostring(m.sender) ..
              " ch=" .. tostring(m.channel) .. " text=" .. tostring(m.text):sub(1, 20))
  msgline:color(C.good)
end

return app
)WADALUA";
static const char kLuaSrc_2048[] = R"WADALUA(-- 2048 — wada.* reference app
-- Swipe (or trackball mapped swipe) to move tiles.
-- Tap after win or game over to restart.

local ui, sys, store, timer = wada.ui, wada.sys, wada.store, wada.timer
local C = ui.colors

local app = {}

local cv, score_lbl

local CELL = 38

local grid = {}

local history = {
    grids = {},
    maxsize = 5
}

local px_w, px_h
local score = 0
local hiscore = 0

local over = false
local won = false


--------------------------------------------------
-- History
--------------------------------------------------

function history:save()

    local old = {
        grid = {},
        score = score,
        over = over,
        won = won
    }

    for x = 1, 4 do

        old.grid[x] = {}

        for y = 1, 4 do
            old.grid[x][y] = grid[x][y]
        end

    end

    table.insert(self.grids, old)

    if #self.grids > self.maxsize then
        table.remove(self.grids, 1)
    end

end


function history:revert()

    if #self.grids > 0 then

        local old = table.remove(self.grids)

        grid = old.grid
        score = old.score
        over = old.over
        won = old.won

    end

end


--------------------------------------------------
-- Game logic
--------------------------------------------------

local function clear_grid()

    grid = {}

    for x = 1, 4 do

        grid[x] = {}

        for y = 1, 4 do
            grid[x][y] = 0
        end

    end

end


--------------------------------------------------
-- Add random tile
--------------------------------------------------

local function add_random_tile()

    local free = {}

    for x = 1, 4 do

        for y = 1, 4 do

            if grid[x][y] == 0 then

                table.insert(
                    free,
                    {
                        x = x,
                        y = y
                    }
                )

            end

        end

    end


    -- Board is full.
    if #free == 0 then
        return false
    end


    local p


    -- If there is only one empty cell,
    -- use it directly.
    if #free == 1 then

        p = free[1]

    else

        local index = sys.random(1, #free)

        if index == nil then
            return false
        end

        p = free[index]

        if p == nil then
            return false
        end

    end


    -- 10% chance for 4,
    -- 90% chance for 2.
    if sys.random(0, 9) == 0 then
        grid[p.x][p.y] = 4
    else
        grid[p.x][p.y] = 2
    end

    return true

end


--------------------------------------------------
-- Reset
--------------------------------------------------

local function reset()

    clear_grid()

    score = 0
    over = false
    won = false

    history.grids = {}

    add_random_tile()
    add_random_tile()

end


--------------------------------------------------
-- Compress line
--------------------------------------------------

local function compress(line)

    local r = {}

    for i = 1, 4 do

        if line[i] ~= 0 then
            table.insert(r, line[i])
        end

    end

    while #r < 4 do
        table.insert(r, 0)
    end

    return r

end


--------------------------------------------------
-- Merge line
--------------------------------------------------

local function merge(line)

    local r = {}
    local i = 1

    while i <= 4 do

        if i < 4
            and line[i] ~= 0
            and line[i] == line[i + 1]
        then

            local v = line[i] * 2

            table.insert(r, v)

            score = score + v


            -- Permanent high score.
            if score > hiscore then

                hiscore = score

                store.set(
                    "2048_best",
                    hiscore
                )

            end


            -- Reaching 2048 means victory.
            if v >= 2048 then
                won = true
            end


            i = i + 2

        else

            table.insert(r, line[i])

            i = i + 1

        end

    end


    while #r < 4 do
        table.insert(r, 0)
    end

    return r

end


--------------------------------------------------
-- Move left
--------------------------------------------------

local function move_left()

    local changed = false

    for y = 1, 4 do

        local old = {}
        local line = {}

        for x = 1, 4 do

            old[x] = grid[x][y]
            line[x] = grid[x][y]

        end


        line = compress(line)
        line = merge(line)


        for x = 1, 4 do

            grid[x][y] = line[x]

            if old[x] ~= line[x] then
                changed = true
            end

        end

    end

    return changed

end


--------------------------------------------------
-- Rotate
--------------------------------------------------

local function rotate()

    local n = {}

    for x = 1, 4 do
        n[x] = {}
    end


    for x = 1, 4 do

        for y = 1, 4 do

            n[y][5 - x] = grid[x][y]

        end

    end


    grid = n

end


--------------------------------------------------
-- Game over
--------------------------------------------------

local function game_over()

    -- Any empty cell means the game can continue.
    for x = 1, 4 do

        for y = 1, 4 do

            if grid[x][y] == 0 then
                return false
            end

        end

    end


    -- Check horizontal and vertical merges.
    for x = 1, 4 do

        for y = 1, 4 do

            if x < 4
                and grid[x][y] == grid[x + 1][y]
            then
                return false
            end


            if y < 4
                and grid[x][y] == grid[x][y + 1]
            then
                return false
            end

        end

    end


    -- Board is full and no merge is possible.
    return true

end


--------------------------------------------------
-- Move
--------------------------------------------------

local function move(dir)

    -- Do nothing after victory or defeat.
    if over or won then
        return
    end


    history:save()

    local changed = false


    if dir == "left" then

        changed = move_left()


    elseif dir == "right" then

        rotate()
        rotate()

        changed = move_left()

        rotate()
        rotate()


    elseif dir == "up" then

        rotate()

        changed = move_left()

        rotate()
        rotate()
        rotate()


    elseif dir == "down" then

        rotate()
        rotate()
        rotate()

        changed = move_left()

        rotate()

    end


    --------------------------------------------------
    -- Nothing moved.
    --------------------------------------------------

    if not changed then

        history:revert()

        return

    end


    --------------------------------------------------
    -- Successful move.
    -- Exactly one new tile must be created.
    --------------------------------------------------

    local added = add_random_tile()


    --------------------------------------------------
    -- This should only happen if the board was already
    -- completely full. Normally a successful move on a
    -- full board creates space, so added should be true.
    --------------------------------------------------

    if not added then

        over = true

        return

    end


    --------------------------------------------------
    -- Victory.
    --
    -- merge() sets won when a 2048 tile is created.
    --------------------------------------------------

    if won then
        return
    end


    --------------------------------------------------
    -- IMPORTANT:
    --
    -- Game-over is checked AFTER the new random tile
    -- has been inserted.
    --------------------------------------------------

    if game_over() then
        over = true
    end

end


--------------------------------------------------
-- Tile colors
--------------------------------------------------

local function tile_color(v)

    if v == 0 then
        return 0xCDC1B4

    elseif v == 2 then
        return 0xEEE4DA

    elseif v == 4 then
        return 0xEDE0C8

    elseif v == 8 then
        return 0xF2B179

    elseif v == 16 then
        return 0xF59563

    elseif v == 32 then
        return 0xF67C5F

    elseif v == 64 then
        return 0xF65E3B

    elseif v == 128 then
        return 0xEDCF72

    elseif v == 256 then
        return 0xEDCC61

    elseif v == 512 then
        return 0xEDC850

    elseif v == 1024 then
        return 0xEDC53F

    elseif v == 2048 then
        return 0xEDC22E

    end

    -- Values above 2048.
    return 0x3C3A32

end


--------------------------------------------------
-- Text colors
--------------------------------------------------

local function text_color(v)

    if v <= 4 then
        return 0x776E65
    else
        return 0xFFFFFF
    end

end


--------------------------------------------------
-- Text size
--------------------------------------------------

local function text_size(v)

    if v < 100 then
        return 16

    elseif v < 1000 then
        return 14

    elseif v < 10000 then
        return 11

    else
        return 9
    end

end


--------------------------------------------------
-- Text positioning
--------------------------------------------------

local function text_x(px, v, size)

    local width

    if v < 100 then
        width = size * 1.1

    elseif v < 1000 then
        width = size * 1.7

    elseif v < 10000 then
        width = size * 2.3

    else
        width = size * 2.9
    end


    return px + math.floor(
        (CELL - width) / 2
    )

end


local function text_y(py, size)

    return py + math.floor(
        (CELL - size) / 2
    )

end


--------------------------------------------------
-- Score line
--------------------------------------------------

local function scoreline()

    local status = ""

    if won then

        status = "   - tap retry"

    elseif over then

        status = "   - tap retry"

    end


    score_lbl:set(
        string.format(
            "Score %d   Best %d%s",
            score,
            hiscore,
            status
        )
    )

end


--------------------------------------------------
-- Draw
--------------------------------------------------

local function draw()

    cv:fill(0x101418)


    for x = 1, 4 do

        for y = 1, 4 do

            local px = (x - 1) * CELL
            local py = (y - 1) * CELL

            local v = grid[x][y]


            cv:rect(
                px + 2,
                py + 2,
                CELL - 4,
                CELL - 4,
                tile_color(v),
                true,
                4
            )


            if v > 0 then

                local size = text_size(v)

                cv:text(
                    text_x(px, v, size),
                    text_y(py, size),
                    tostring(v),
                    text_color(v),
                    size
                )

            end

        end

    end


    --------------------------------------------------
    -- End messages
    --------------------------------------------------

    if won then

        cv:text(
            30,
            px_h / 2,
            "YOU WIN!",
            C.good,
            18
        )

    elseif over then

        cv:text(
            30,
            px_h / 2,
            "GAME OVER",
            C.bad,
            18
        )

    end

end


--------------------------------------------------
-- WADAMESH API
--------------------------------------------------

function app.on_open(w, h)

    hiscore = store.get(
        "2048_best",
        0
    )


    px_w = CELL * 4
    px_h = CELL * 4


    score_lbl = ui.label(
        "",
        4,
        4,
        14,
        C.text
    )


    cv = ui.canvas(
        px_w,
        px_h
    )


    cv:pos(
        math.floor(
            (w - px_w) / 2
        ),
        28
    )


    reset()

    scoreline()
    draw()


    timer.every(100)

end


function app.on_input(ev)

    if ev.type == "swipe" then

        move(ev.dir)

        scoreline()
        draw()


    elseif ev.type == "down"
        and (over or won)
    then

        reset()

        scoreline()
        draw()

    end

end


function app.on_tick(dt)

end


function app.on_close()

end


return app
)WADALUA";
static const char kLuaSrc_wardrive[] = R"WADALUA(-- Wardrive (Lua) — a LoRa coverage survey that logs to a CSV you can pull off
-- the device afterwards.
--
-- Reference app for the discovery half of the SDK. It works the way a survey
-- has to work: it PROBES rather than listens. A probe is a zero-hop request
-- that every node in earshot answers, so a reply proves the link works from
-- exactly where you are standing. Listening only ever tells you what happened
-- to transmit while you were there, which is a different and much weaker claim.
--
-- Each reply carries both directions of the link: how well we heard them, and
-- how well they heard us. They are rarely equal, and the asymmetry is the point
-- -- "I can hear the repeater but it cannot hear me" is not the same fact as
-- "no coverage", and only a probe reveals it.
local ui, sys, mesh, fs, timer = wada.ui, wada.sys, wada.mesh, wada.fs, wada.timer
local C = ui.colors
local app = {}

local SWEEP_MS = 20000        -- above the 15 s floor the firmware enforces on probes
local HARVEST_MS = 4000       -- replies land over the few seconds after a probe
local TYPE = { [1]="chat", [2]="repeater", [3]="room", [4]="sensor" }

local run, running, samples, sweeps, last_err = "run", false, 0, 0, nil
local node_count = 0
local phase, phase_at = "idle", 0
local hdr, gps_lbl, stat_lbl, rows = nil, nil, nil, {}
local nodes = {}              -- pubkey -> { name, type, best, worst, seen }
local pending = {}            -- lines waiting on the 1 write/sec limit

local function logname() return run .. ".csv" end

-- Lua here is built with 32-bit floats, so fix.lat is good to about a metre and
-- no better. fix.lat_e6 is the same reading as an exact integer in
-- micro-degrees, which is what belongs in a log: a survey you plot months later
-- should not carry rounding the device never had.
local HEADER = "epoch,lat_e6,lon_e6,alt_m,pubkey,name,type,rssi,snr,their_snr,hops"
local wrote_header = false

-- The filesystem allows one write a second. Sweeps produce a burst of rows, so
-- they queue here and drain a chunk per tick instead of being dropped.
local function flush()
  if #pending == 0 then return end
  local chunk = table.concat(pending, "\n") .. "\n"
  if not wrote_header then chunk = HEADER .. "\n" .. chunk end
  local ok = fs.append(logname(), chunk)
  if ok then pending, wrote_header = {}, true end
end

local function record(fix, hit)
  local key = hit.pubkey
  local n = nodes[key]
  if not n then
    n = { name = hit.name or key, type = hit.type, best = hit.snr, worst = hit.snr, seen = 0 }
    nodes[key] = n
    node_count = node_count + 1
  end
  if hit.snr > n.best  then n.best  = hit.snr end
  if hit.snr < n.worst then n.worst = hit.snr end
  n.seen = n.seen + 1
  if hit.name then n.name = hit.name end

  samples = samples + 1
  pending[#pending + 1] = string.format("%d,%d,%d,%d,%s,%s,%d,%d,%.2f,%.2f,%d",
    fix.time or sys.epoch(), fix.lat_e6, fix.lon_e6, fix.alt_m or 0,
    key, (hit.name or ""):gsub(",", " "), hit.type,
    hit.rssi, hit.snr, hit.their_snr, hit.hops)
end

local function sweep()
  local tag, err = mesh.discover()          -- every node type
  if not tag then last_err = err; return false end
  last_err = nil
  sweeps = sweeps + 1
  return true
end

local function harvest()
  local fix = sys.gps()
  if not fix then
    -- No fix means the sample cannot be placed, so it is discarded rather than
    -- logged at 0,0. A survey file with phantom points at Null Island is worse
    -- than a shorter one.
    mesh.discover_clear()
    return
  end
  for _, hit in ipairs(mesh.discovered()) do record(fix, hit) end
  mesh.discover_clear()                     -- next sample must not inherit this one
end

local function redraw()
  local fix = sys.gps()
  if fix then
    gps_lbl:set(string.format("%.5f, %.5f  %dm  %d sats", fix.lat, fix.lon, fix.alt_m or 0, fix.sats))
    gps_lbl:color(C.good)
  else
    gps_lbl:set("waiting for a GPS fix - samples are discarded until then")
    gps_lbl:color(C.bad)
  end

  local state = running and (phase == "probe" and "listening..." or "sweeping") or "stopped"
  stat_lbl:set(string.format("%s  |  %s  |  %d sweeps, %d samples, %d nodes%s",
    run, state, sweeps, samples, node_count,
    last_err and ("  [" .. last_err .. "]") or ""))
  stat_lbl:color(last_err and C.bad or C.accent)

  local list = {}
  for key, n in pairs(nodes) do list[#list + 1] = { key = key, n = n } end
  table.sort(list, function(a, b) return a.n.best > b.n.best end)
  for i = 1, #rows do
    local e = list[i]
    if e then
      rows[i]:set(string.format("%-14s %-8s best %5.1f  worst %5.1f  x%d",
        e.n.name:sub(1, 14), TYPE[e.n.type] or "?", e.n.best, e.n.worst, e.n.seen))
      rows[i]:color(e.n.best > 0 and C.good or C.text)
    else
      rows[i]:set(i == 1 and "nothing has answered a probe yet" or "")
      rows[i]:color(C.sub)
    end
  end
end

function app.on_open(w, h)
  if not sys.caps().discover then
    ui.label("This board does not carry the extended SDK,", 6, 8, 12, C.bad)
    ui.label("so it cannot send discovery probes.", 6, 26, 12, C.bad)
    return
  end
  ui.scroll(true)
  local LH = ui.text_h(12)
  local y = 4

  hdr = ui.label("LoRa coverage survey", 4, y, 12, C.accent); hdr:width(w - 10); y = y + LH + 3
  gps_lbl = ui.label("", 4, y, 12, C.sub); gps_lbl:width(w - 10); y = y + LH + 3
  stat_lbl = ui.label("", 4, y, 12, C.text); stat_lbl:width(w - 10); y = y + LH * 2 + 5

  local bw = math.min(96, (w - 20) // 3)
  ui.button("Start", 4, y, bw, 32, function()
    running = not running
    if running then phase, phase_at = "idle", 0 end
    sys.toast(running and "Survey running" or "Survey stopped", 1200)
  end)
  ui.button("Name", 8 + bw, y, bw, 32, function()
    ui.input("Name this run", run, function(text)
      if text then
        run = text:gsub("[^%w%-_]", "_")
        wrote_header = false          -- a new file needs its own header row
        sys.toast("Logging to " .. logname(), 1500)
      end
    end)
  end)
  ui.button("Reset", 12 + bw * 2, y, bw, 32, function()
    nodes, samples, sweeps, pending, node_count = {}, 0, 0, {}, 0
    mesh.discover_clear()
    fs.remove(logname())
    wrote_header = false
    sys.toast("Cleared " .. logname(), 1200)
  end)
  y = y + 38

  ui.label("strongest first", 4, y, 12, C.sub); y = y + LH + 2
  for i = 1, 12 do
    rows[i] = ui.label("", 4, y, 12, C.text); rows[i]:width(w - 10); y = y + LH + 2
  end

  redraw()
  timer.every(1000)
end

function app.on_tick()
  if running then
    local now = sys.millis()
    if phase == "idle" or (phase == "wait" and now - phase_at >= SWEEP_MS) then
      -- A refused or rate-limited probe backs off a full sweep interval. Retrying
      -- every tick would re-enter the permission path once a second for nothing.
      phase, phase_at = sweep() and "probe" or "wait", now
    elseif phase == "probe" and now - phase_at >= HARVEST_MS then
      harvest()
      phase = "wait"          -- phase_at stays at the probe time, so sweeps stay on cadence
    end
  end
  flush()
  redraw()
end

function app.on_close()
  flush()                     -- one last drain; anything queued would otherwise be lost
end

return app
)WADALUA";
static const char kLuaSrc_nearby[] = R"WADALUA(-- Nearby (Lua) — contacts on a real map, with distance and bearing, and a live
-- packet counter.
--
-- Reference app for the four things the SDK gained alongside it: wada.map (the
-- firmware's own tiles inside an app page), wada.ui.list (scrollable selectable
-- rows), app.on_packet (each frame delivered once instead of polled), and
-- wada.geo (great-circle maths in C rather than in your instruction budget).
local ui, sys, mesh, geo, timer = wada.ui, wada.sys, wada.mesh, wada.geo, wada.timer
local C = ui.colors
local app = {}

local map, list, hdr, detail = nil, nil, nil, nil
local pts, sel = {}, 0
local pkt_count, pkt_adverts = 0, 0
local W, H

local function here()
  local fix = sys.gps()
  if fix then return fix.lat, fix.lon, true end
  local me = mesh.self()
  -- self() is the last known position, which may be old. Say which one is in
  -- use rather than presenting a stale fix as a live one.
  if me.lat ~= 0 or me.lon ~= 0 then return me.lat, me.lon, false end
  return nil
end

local function fmt_dist(m)
  if m < 1000 then return string.format("%.0f m", m) end
  return string.format("%.1f km", m / 1000)
end

local function rebuild()
  local lat, lon, live = here()
  pts, sel = {}, 0
  for _, c in ipairs(mesh.contacts()) do
    if c.lat ~= 0 or c.lon ~= 0 then
      local e = { name = c.name, lat = c.lat, lon = c.lon, type = c.type, pubkey = c.pubkey }
      if lat then
        e.dist = geo.distance(lat, lon, c.lat, c.lon)
        e.brg  = geo.bearing(lat, lon, c.lat, c.lon)
      end
      pts[#pts + 1] = e
    end
  end
  if lat then table.sort(pts, function(a, b) return (a.dist or 1e9) < (b.dist or 1e9) end) end

  list:clear()
  for i, e in ipairs(pts) do
    local label = e.dist
      and string.format("%-12s  %8s  %-2s", e.name:sub(1, 12), fmt_dist(e.dist), geo.cardinal(e.brg))
      or  e.name
    list:add(label, function() app.pick(i) end)
  end
  if #pts == 0 then list:add("no contacts have a position yet") end

  hdr:set(string.format("%d placed  |  %s  |  %d frames (%d adverts)",
    #pts, lat and (live and "GPS fix" or "last known position") or "no position", pkt_count, pkt_adverts))
  hdr:color(lat and C.accent or C.bad)

  if lat then app.draw(lat, lon) end
end

function app.draw(lat, lon)
  if not map then return end
  map:center(lat, lon)
  map:clear()
  if map:tiles() == 0 then
    -- An empty rectangle looks like open water. Say what it actually is.
    detail:set("no map tiles cached here at zoom " .. map:zoom())
    detail:color(C.sub)
  end
  for i, e in ipairs(pts) do
    map:line(lat, lon, e.lat, e.lon, i == sel and C.good or 0x2A3340, i == sel and 2 or 1)
  end
  for i, e in ipairs(pts) do
    map:marker(e.lat, e.lon, i == sel and C.good or C.accent, i == sel and 12 or 8)
  end
  map:marker(lat, lon, 0xE8A33D, 10)      -- us, last so it sits on top
end

function app.pick(i)
  sel = i
  list:select(i)
  local e = pts[i]
  if not e then return end
  local lat, lon = here()
  if e.dist then
    detail:set(string.format("%s  %s  %.0f deg (%s)  %s",
      e.name, fmt_dist(e.dist), e.brg, geo.cardinal(e.brg), e.pubkey))
  else
    detail:set(e.name .. "  " .. e.pubkey)
  end
  detail:color(C.text)
  if lat then app.draw(lat, lon) end
end

function app.on_open(w, h)
  W, H = w, h
  local LH = ui.text_h(12)
  hdr = ui.label("", 4, 4, 12, C.accent); hdr:width(w - 10)

  -- hdr and detail below are width-limited, which turns wrapping on, and both
  -- carry variable-length text (node names, a status phrase). Reserve two lines
  -- for each: a wrapped line would otherwise be drawn over by whatever follows.
  local map_h = math.floor(h * 0.45)
  local y = 4 + LH * 2 + 4
  if sys.caps().map then
    map = wada.map.view(4, y, w - 8, map_h)
  else
    ui.label("this board has no map support", 6, y + 10, 12, C.sub)
  end
  y = y + map_h + 4

  detail = ui.label("pick a contact", 4, y, 12, C.sub); detail:width(w - 10)
  y = y + LH * 2 + 4

  list = ui.list(4, y, w - 8, h - y - 4)

  rebuild()
  -- Two cadences, which is what wada.timer.after/every made possible: a slow
  -- rebuild (contacts and GPS move slowly) and no fast tick at all, because
  -- packets now arrive by callback instead of being polled for.
  timer.every(5000, rebuild)
end

-- One call per frame the radio received, in arrival order. Counting was simply
-- not possible against a polled 16-entry ring.
function app.on_packet(p)
  pkt_count = pkt_count + 1
  if p.pubkey then pkt_adverts = pkt_adverts + 1 end
end

function app.on_close()
  if map then map:close() end
end

return app
)WADALUA";

static const LuaBuiltinApp kLuaBuiltin[] = {
  { "monitor", "RF Monitor", "1.3", kLuaSrc_monitor },
  { "airtime", "Airtime", "1.4", kLuaSrc_airtime },
  { "snake", "Snake", "1.0", kLuaSrc_snake },
  { "sdktest", "SDK Test", "1.7", kLuaSrc_sdktest },
  { "2048", "2048", "1.2", kLuaSrc_2048 },
  { "wardrive", "Wardrive", "1.0", kLuaSrc_wardrive },
  { "nearby", "Nearby", "1.0", kLuaSrc_nearby },
};
static const int kLuaBuiltinCount = (int)(sizeof(kLuaBuiltin)/sizeof(kLuaBuiltin[0]));
